name: check_code_quality
on: pull_request
jobs:
  black:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: |
          python -m pip install --upgrade pip
          pip install black
      - run: |
          black --check --verbose .